version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-short-backend
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped

  client:
    build:
      context: ./caption
      dockerfile: Dockerfile
    container_name: ai-short-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./caption:/app
    depends_on:
      - server
    restart: unless-stopped
